export const SET_PDF_PATH = 'SET_PDF_PATH';
export const SET_SELECTED_PHRASE = 'SET_SELECTED_PHRASE';
export const SET_REMOTE_VOCABULARY = 'SET_REMOTE_VOCABULARY';
export const SET_REQUEST = 'SET_REQUEST';
