export const POPULATE_GAME_ANSWERS_FROM_LOCAL = 'POPULATE_GAME_ANSWERS_FROM_LOCAL';
export const REQUEST_POPULATE_GAME_ANSWERS_FROM_LOCAL = 'REQUEST_POPULATE_GAME_ANSWERS_FROM_LOCAL';
export const UPDATE_GAME = 'UPDATE_GAME';
export const REQUEST_UPDATE_GAME = 'REQUEST_UPDATE_GAME';
