export const SYNC_VOCABULARIES = 'SYNC_VOCABULARIES';
export const SYNC_VOCABULARY = 'SYNC_VOCABULARY';
export const CHECK_VOCABULARY_SYNC_STATUS = 'CHECK_VOCABULARY_SYNC_STATUS';
export const IMPORT_VOCABULARY = 'IMPORT_VOCABULARY';
export const ADD_VOCABULARY = 'ADD_VOCABULARY';
export const DELETE_VOCABULARY = 'DELETE_VOCABULARY';
export const EDIT_VOCABULARY = 'EDIT_VOCABULARY';
export const POPULATE_VOCABULARIES_FROM_LOCAL = 'POPULATE_VOCABULARIES_FROM_LOCAL';
export const POPULATE_VOCABULARY_FROM_LOCAL = 'POPULATE_VOCABULARY_FROM_LOCAL';
export const POPULATE_VOCABULARY_FROM_REMOTE = 'POPULATE_VOCABULARY_FROM_REMOTE';
export const POPULATE_REMOTE_VOCABULARIES = 'POPULATE_REMOTE_VOCABULARIES';
export const POPULATE_REMOTE_VOCABULARY_PHRASES = 'POPULATE_REMOTE_VOCABULARY_PHRASES';

export const ADD_PHRASE = 'ADD_PHRASE';
export const DELETE_PHRASE = 'DELETE_PHRASE';
export const EDIT_PHRASE = 'EDIT_PHRASE';

export const SET_VOCABULARY_SELECTED = 'SET_VOCABULARY_SELECTED';

export const REQUEST_GET_REMOTE_VOCABULARY = 'REQUEST_GET_REMOTE_VOCABULARY';
export const REQUEST_GET_REMOTE_VOCABULARY_PHRASES = 'REQUEST_GET_REMOTE_VOCABULARY_PHRASES';
export const REQUEST_SYNC_VOCABULARIES = 'REQUEST_SYNC_VOCABULARIES';
export const REQUEST_SYNC_VOCABULARY = 'REQUEST_SYNC_VOCABULARY';
export const REQUEST_ADD_VOCABULARY = 'REQUEST_ADD_VOCABULARY';
export const REQUEST_DELETE_VOCABULARY = 'REQUEST_DELETE_VOCABULARY';
export const REQUEST_EDIT_VOCABULARY = 'REQUEST_EDIT_VOCABULARY';
export const REQUEST_POPULATE_VOCABULARIES_FROM_LOCAL = 'REQUEST_POPULATE_VOCABULARIES_FROM_LOCAL';
export const REQUEST_POPULATE_REMOTE_VOCABULARIES = 'REQUEST_POPULATE_REMOTE_VOCABULARIES';
export const REQUEST_IMPORT_VOCABULARY = 'REQUEST_IMPORT_VOCABULARY';
export const REQUEST_ADD_VOCABULARY_ADD_PHRASE = 'REQUEST_ADD_VOCABULARY_ADD_PHRASE';

export const REQUEST_ADD_PHRASE = 'REQUEST_ADD_PHRASE';
export const REQUEST_DELETE_PHRASE = 'REQUEST_DELETE_PHRASE';
export const REQUEST_EDIT_PHRASE = 'REQUEST_EDIT_PHRASE';
