export const ADD_VOCABULARY = 'ADD_VOCABULARY';
export const DELETE_VOCABULARY = 'DELETE_VOCABULARY';
export const EDIT_VOCABULARY = 'EDIT_VOCABULARY';
export const POPULATE_VOCABULARIES = 'POPULATE_VOCABULARIES';

export const ADD_PHRASE = 'ADD_PHRASE';
export const DELETE_PHRASE = 'DELETE_PHRASE';
export const EDIT_PHRASE = 'EDIT_PHRASE';

export const SET_VOCABULARY_SELECTED = 'SET_VOCABULARY_SELECTED';

export const REQUEST_ADD_VOCABULARY = 'REQUEST_ADD_VOCABULARY';
export const REQUEST_DELETE_VOCABULARY = 'REQUEST_DELETE_VOCABULARY';
export const REQUEST_EDIT_VOCABULARY = 'REQUEST_EDIT_VOCABULARY';
export const REQUEST_POPULATE_VOCABULARIES = 'REQUEST_POPULATE_VOCABULARIES';
