const {
  REACT_APP_AUTH0_CLIENT_ID,
  REACT_APP_AUTH0_DOMAIN,
  REACT_APP_REDIRECT_URL,
  REACT_APP_AUTH0_AUDIENCE,
} = process.env;
export default {
  AUTH0_CLIENT_ID: REACT_APP_AUTH0_CLIENT_ID,
  AUTH0_DOMAIN: REACT_APP_AUTH0_DOMAIN,
  REDIRECT_URL: REACT_APP_REDIRECT_URL,
  AUTH0_AUDIENCE: REACT_APP_AUTH0_AUDIENCE,
};
